version: '3.6'
services:
  Elasticsearch:
    image: elasticsearch:7.16.2
    container_name: elasticsearch
    restart: always
    volumes:
    - elastic_data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node    
    ports:
    - '9200:9200'
    - '9300:9300'
    networks:
      - elk

  Logstash:
    image: logstash:7.16.2
    container_name: logstash
    restart: always
    volumes:
    - ./logstash/:/logstash_dir
    - /home/ubuntu/suricata/logs:/suricata_logs:ro
    command: logstash -f /logstash_dir/logstash.conf 
    depends_on:
      - Elasticsearch
    ports:
    - '9600:9600'
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"    
    networks:
      - elk

  Kibana:
    image: kibana:7.16.2
    container_name: kibana
    restart: always       
    ports:
    - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200  
    depends_on:
      - Elasticsearch  
    networks:
      - elk

  Elastalert2:
    image: jertel/elastalert2
    container_name: elastalert2
    restart: always
    environment:
      - "ES_HOST=elasticsearch"
      - "ES_PORT=9200"
      - "KIBANA_HOST=kibana:5601"
    volumes:
      - ./elastalert/config/config.yaml:/opt/elastalert/config.yaml
      - ./elastalert/rules:/opt/elastalert/rules
    depends_on:
      - Elasticsearch
    ports:
      - "3030:3030"  # ElastAlert2 ´ëº¸µå÷(¼±Å »ç)
    networks:
      - elk

volumes:
  elastic_data: {}

networks:
  elk:
