es_host: elasticsearch
es_port: 9200
rules_folder: /opt/elastalert/rules
timestamp_field: "@timestamp"
timestamp_type: iso
writeback_index: elastalert_status
run_every:
  minutes: 1
buffer_time:
  minutes: 15
alert_time_limit:
  days: 2
alert:
  - "slack"
slack_webhook_url: "https://hooks.slack.com"

